seiar:
  _target_: envs.SeiarEnvironment
  beta: 0.0000000132339796
  psi: 0.7
  nu_daily_max: 500000
  nu_total_max: 5000000
  kappa: 0.7143
  alpha: 0.1667
  tau: 0.0
  p: 0.667
  eta: 0.1667
  f: 0.999
  epsilon: 0.0
  q: 0.5
  delta: 0.5
  S0: 50000000
  E0: 0
  I0: 1
  A0: 0
  R0: 0
  tf: 300
  dt: 1.0

clip_range: 0.8
lr: 0.0015
n_steps: 9_000_000
# n_step/tf = n_episodes
  
hydra:
  job:
    chdir: true